@extends('template/main')
@section('header')
  @include('template/header')
@endsection
@section('main')
  @include('template/contenedor')
@endsection
@section('footer')
  @include('template/footer')
@endsection
